### ISSUE TITLE
Add my own script after launch

### ISSUE THREAD

**Issue by MisterH001** [drud/ddev-gitpod-launcher#21]
Hi Randy
I was wondering if it is possible to add something to my repo (ideally a bash script) which will be automatically run on start/launch - while still using your launcher UI?
This is so I can run a bash script to update the base urls for a Magento 2 project.
Thank you!

**Comment by rfay** [comment]
How about a pre-start exec-host hook that runs the script (or does the job itself?)

**Comment by MisterH001** [comment]
Thanks Randy, that's a great idea.
So would I just create an empty .ddev folder with a basic config.yaml file that would only contain that info? e.g.:
```
hooks:
  post-start:
    - exec: "simple command expression"
    - exec: "ls >/dev/null && touch /var/www/html/somefile.txt"
    - exec-host: "simple command expression"
  post-import-db:
    - exec: "drush uli"

```
Would that conflict with the automatically generated .ddev/config.yaml file?
Thanks!
